### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by klappy**
Release candidate for v2.0.0.

- Simplified usage, all with a single function `tokenize({text, ...options})`.
- Improved performance.
- Much more flexible and adaptable.
- Many more tests added.
- Documentation/Playground added: [Here](https://unfoldingword.github.io/string-punctuation-tokenizer/#/Tokenize)
- Many options include: 
  - text {string}: The string to be tokenized.
  - includeWords {bool}: Include the word tokens in the output.
  - includeNumbers {bool}: Include the number tokens in the output.
  - includePunctuation {bool}: Include the punctuation tokens in the output.
  - includeWhitespace {bool}: Include the whitespace tokens in the output.
  - greedy {bool}: Use Greedy Tokens, overridden by parsers.
  - verbose {bool}: Output an array of token objects with types.
  - occurrences {bool}: Output occurrence and occurrences for each token, requires verbose.
  - parsers {object}: Override the internal token classifier's Regular Expressions for {word, number, punctuation, whitespace}.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/string-punctuation-tokenizer/43)

### CODE REVIEW

**Comment by klappy** [comment]
___
*[src/occurrences.js, line 34 at r1](https://reviewable.io/reviews/unfoldingword/string-punctuation-tokenizer/43#-LyFmHJ_CRv9EOAszFFn:-LyUvM4J0VgFIjn_e8Si:b3pkkf0) ([raw file](https://github.com/unfoldingword/string-punctuation-tokenizer/blob/f32339ab7aa9f9a7da7c9b4feefeeca0809a913d/src/occurrences.js#L34)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do we need a check for `token` here as well before `token.token` If some reason it receives `tokens = [null]`
</blockquote></details>

Good catch!

**Comment by klappy** [comment]
@neutrinog Can you create an issue for that so we can add that as a feature request? This PR is attempting to get the current latest code that is on NPM updated to the default branch. We can add that feature for the next release pretty easily.

**Comment by neutrinog** [comment]
@klappy  sure thing. https://github.com/unfoldingWord/string-punctuation-tokenizer/issues/44

**Comment by PhotoNomad0** [comment]
@klappy - it looks like this is waiting on you to respond to @RoyalSix 's suggestion.

**Comment by klappy** [comment]
___
*[src/occurrences.js, line 34 at r1](https://reviewable.io/reviews/unfoldingword/string-punctuation-tokenizer/43#-LyFmHJ_CRv9EOAszFFn:-M2Va3NyBQgkXhugHSGz:b-896fix) ([raw file](https://github.com/unfoldingword/string-punctuation-tokenizer/blob/f32339ab7aa9f9a7da7c9b4feefeeca0809a913d/src/occurrences.js#L34)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Good catch! 
</blockquote></details>

Done.

**Comment by klappy** [comment]
@photonomad0 Thanks for the reminder!

**Comment by klappy** [comment]
All issues are addressed.

**Pull request merged**
